'use strict';

module.exports = {
  // Address: require('./address.js'),
  // Access: require('./access.js'),
  // Accounting: require('./accounting.js'),
  // Activity: require('./activity.js'),
  // Admin: require('./admin.js'),
  // Amenity: require('./amenities.js'),
  // App: require('./app.js'),
  // Application: require('./application.js'),
  // Api: require('./api.js'),
  // Billing: require('./billing.js'),
  // Charge: require('./charges.js'),
  // Checklist: require('./checklists.js'),
  // Company: require('./company.js'),
  Contact: require('./contact.js'),
  // ContactLeases: require('./contact_leases.js'),
  // Cosigner: require('./cosigners.js'),
  // Credentials: require('./credentials.js'),
  // Dashboard: require('./dashboard.js'),
  // Discount: require('./discounts.js'),
  Delinquency: require('./delinquency.js'),
  DelinquencyPause: require('./delinquencies_pause.js'),
  DelinquencyAction: require('./delinquencies_action.js'), 
  // Document: require('./documents.js'),
  // DocumentSign: require('./document_signs.js'),
  // Email: require('./email.js'),
  // Event: require('./event.js'),
  // Hours: require('./hours.js'),
  // Insurance: require('./insurance.js'),
  // Interaction: require('./interaction.js'),
  Invoice: require('./invoice.js'),
  InvoiceLines: require('./invoice_lines.js'),
  InvoicesPayments: require('./invoices_payments.js'),
  Lead: require('./lead.js'),
  Lease: require('./lease.js'),
  // LeaseTemplate: require('./lease-templates.js'),
  // Maintenance: require('./maintenance.js'),
  // MaintenanceExtra: require('./maintenance-extras.js'),
  // MaintenanceType: require('./maintenance-types.js'),
  // Notification: require('./notifications.js'),
  Payment: require('./payment.js'),
  PaymentMethod: require('./payment_method.js'),
  // Product: require('./products.js'),
  // ProductCategory: require('./product_category.js'),
  // Promotion: require('./promotions.js'),
  Property: require('./property.js'),
  PropertyAddress: require('./property_address.js'),
  // PropertyGroup: require('./property_groups.js'),
  RentChange: require('./rent_change.js'),
  // Report: require('./reports.js'),
  // ReportQueries: require('./report_queries.js'),
  // Reservation: require('./reservation.js'),
  // Role: require('./roles.js'),
  // Setting: require('./settings.js'),
  // Service: require('./service.js'),
  // Summary: require('./summary.js'),
  // Deposit: require('./deposits.js'),
  // TaxLine: require('./tax-lines.js'),
  Tenant: require('./tenant.js'),
  // Todo: require('./todo.js'),
  // Touchpoint: require('./touchpoint.js'),
  // Trigger: require('./trigger.js'),
  // TriggerGroup: require('./trigger_group.js'),
  UnitCategory: require('./unit_category.js'),
  Unit: require('./unit.js'),
  Auction: require('./lease_auction.js'),
  // Upload: require('./upload.js'),
  // User: require('./user.js'),
  // Vendor: require('./vendors.js'),
  // LeaseStanding: require('./lease_standing'),
  // Phone_Call: require('./phone_call')
  Refund: require('./refund.js'),
  Todos: require('./todos.js'),
  Common: require('./common.js'),
  InvoiceLinesAllocation: require('./invoice_lines_allocation.js'),
  Promotion: require('./promotion.js'),
  AccountingExport: require('./accounting_exports.js'),
  PropertyRateManagement: require('./property_rate_management'),
  PropertyRentManagement: require('./property_rent_management'),
  RentChangeDeploymentMonth: require('./rent_change_deployment_month'),
  ReviewRentChanges: require('./review_rent_changes.js'),
  TenantRentManagement: require('./tenant_rent_management.js'),
  AdditionalContact: require('./additional_contacts.js') 
};
