
const LOGGING = Object.freeze({
    ACCOUNTING: 'AccountingLoggerEvent',
    ACCOUNTING_RESILIENCY: 'AccountingResiliencyLoggerEvent',
    GENERATE_DOCUMENT: 'GenerateDocumentLoggerEvent',
    SHARE_REPORT: 'ShareReportLoggerEvent',
    GENERATE_INVOICE: 'GenerateInvoiceEvent',
    DELINQUENCY_PROCESS: 'DelinquencyProcess',
    AUTO_PAYMENT: 'AutoPaymentEvent',
    RATE_MANAGEMENT_CRON: 'RateManagementCron',
    RENT_MANAGEMENT_CRON: 'RentManagementCron',
    UPLOAD_RENT_CHANGE: 'UploadRentChanges',
    RESET_DELINQUENCY_ACTIONS: 'ResetDelinquencyActions',
    SEND_SHARE_REPORT: "SendScheduleReportEvent",
    SHARE_REPORTS_PAYLOAD: "ScheduleReportsEvent",
    GENERATE_SHARE_REPORTS: "GenerateScheduleReportEvent",
    PAYMENT_CYCLE_REVERSION: "PaymentCycleReversion",
    ADVANCED_RENTALS: "AdvancedRentalsLoggerEvent",
    GATE_ACCESS: "gateAccess",
    SEND_SMS: "sendSMS",
    SEND_EMAIL: "SendEmail",
    MIGRATE_ACCOUNTING: "MigrateAccounting",
    AUDITING: "Auditing",
    INVOICE_CONSOLIDATION: "InvoiceConsolidation",
    AUTO_RETIRE_LEAD: "AutoRetireLead",
    SEND_EMAIL_INVOICE: "SendEmailInvoice",
    ACCOUNTING_TRANNUM: "AccountingTrannum",
    INVOICE_NUMBER: "InvoiceNumber",
    EXECUTE_SCRIPTS: "ExecuteScripts",
    UPDATE_PROMOTION_UNITS: 'UpdatePromotionUnits',
    PROCESS_REVERSAL: "ProcessReversal",
});
  
module.exports = LOGGING; 