const EVENTS = Object.freeze({
  PAYMENT_PROCESSED: "PAYMENT_PROCESSED",
  GENERATE_EVENT_EXPORT: "GENERATE_EVENT_EXPORT",
  PROMOTION_UNIT_UPDATE : "PROMOTION_UNIT_UPDATE",
  END_DELINQUENCY: "END_DELINQUENCY",
  REFUND_PROCESSED: "REFUND_PROCESSED"
});

module.exports = EVENTS;