
module.exports = {

	'/':{
		get: 'id,company_id,user_id,salutation,status,first,middle,last,suffix,email,notes,gender,company,ssn,dob,driver_license,driver_license_city,driver_license_state,driver_license_country,driver_license_exp,active_military,have_secondary_contact,military_branch,Military(*),Business(*),Employment(*),Vehicles(*),Relationships(id,related_contact_id,lease_id,type,is_cosigner,is_emergency,is_alternate,is_military,is_authorized,is_lien_holder,Contact(id,company_id,user_id,salutation,status,first,middle,last,suffix,email,notes,gender,company,ssn,dob,driver_license,driver_license_city,driver_license_state,driver_license_country,driver_license_exp,active_military,have_secondary_contact,military_branch)),Phones(id,type,phone,sms,primary),Addresses(type,Address(address,address2,city,state,neighborhood,zip,country,lat,lng))',
	},
	'/omni-search':{
		post: 'id,contact_id,salutation,first,middle,last,suffix,email,company,dob,ssn,gender,driver_license,active_military,military_branch,email,status,source,created,notes,content,Phones(id,type,phone,sms),Addresses(type,address,address2,city,state,neighborhood,zip,country,lat,lng)',
	},
	// '/:contact_id':{
	// 	get: 'id,company_id,user_id,salutation,first,middle,last,suffix,email,notes,gender,company,ssn,dob,driver_license,driver_license_city,driver_license_state,driver_license_exp,active_military,military_branch,military(military_email,military_branches,military_contact_first_name,military_contact_last_name,military_unit_name,military_phone,military_identification_number,military_expiration,military_service_member_DOB,military_rank,military_address_additional_info,military_state,military_zip,military_city,military_address),source,status,Pending(*),Reservations(id,lease_id,expires,created,time,Lease(id,unit_id,start_date,end_date,bill_day,terms,rent,notes,promotion_id,Unit(id,property_id,category_id,number,price,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng)))),Employment(*),Vehicles(*),Relationships(id,related_contact_id,lease_id,type,is_cosigner,is_alternate,is_emergency,is_military,is_authorized,is_lien_holder,Contact(id,contact_id,salutation,first,middle,last,suffix,email,Phones(id,type,phone,sms),Addresses(type,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)))),Phones(id,type,phone,sms),Addresses(type,move_in,move_out,rent,landlord,phone,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)),Leases(id,unit_id,promotion_id,start_date,end_date,bill_day,notes,terms,rent,status,send_invoice,balance,security_deposit,monthly,Unit(id,property_id,category_id,address_id,number,type,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng))',
	// 	get_api: 'id,company_id,user_id,salutation,first,middle,last,suffix,email,gender,company,ssn,dob,driver_license,driver_license_city,driver_license_state,driver_license_exp,active_military,military_branch,military(military_email,military_branches,military_contact_first_name,military_contact_last_name,military_unit_name,military_phone,military_identification_number,military_expiration,military_service_member_DOB,military_rank,military_address_additional_info,military_state,military_zip,military_city,military_address),source,Reservations(id,lease_id,expires,created,time,Lease(id,unit_id,end_date,bill_day,terms,rent,promotion_id,Unit(id,property_id,category_id,number,price,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng)))),Employment(*),Vehicles(*),Relationships(id,related_contact_id,lease_id,type,is_cosigner,is_alternate,is_emergency,is_military,is_authorized,is_lien_holder,Contact(id,contact_id,salutation,first,middle,last,suffix,email,Phones(id,type,phone,sms),Addresses(type,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)))),Phones(id,type,phone,sms),Addresses(type,move_in,move_out,rent,landlord,phone,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)),Leases(id,unit_id,promotion_id,start_date,end_date,bill_day,notes,terms,rent,status,send_invoice,balance,security_deposit,monthly,Unit(id,property_id,category_id,address_id,number,type,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng))',
	// },
	'/:contact_id':{
		get: 'id,company_id,user_id,salutation,status,first,middle,last,suffix,email,verification_token,email_verified,notes,gender,company,ssn,dob,driver_license,driver_license_city,driver_license_state,driver_license_country,driver_license_exp,active_military,have_secondary_contact,military_branch,Military(id,Phone(id,phone,sms,type,country_code),CommandingOfficer(first,last,email,Phone(id,phone,sms,type,country_code)),active,service_member_email,branch,unit_name,identification_number,service_expiration,date_of_birth,rank,Address(id,address,address2,city,state,zip,country)),Business(id,name,phone_type,phone,country_code,Address(address,address2,city,state,zip,country)),source,status,Pending(*),Lead(*),Reservations(id,lease_id,expires,created,time,Lease(id,unit_id,start_date,end_date,bill_day,terms,rent,sensitive_info_stored,auto_pay_after_billing_date,notes,promotion_id,security_deposit,Unit(id,property_id,category_id,number,price,state,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng)))),Employment(*),Vehicles(*),Relationships(id,related_contact_id,lease_id,type,is_alternate,is_cosigner,is_emergency,is_military,is_authorized,is_lien_holder,Contact(id,contact_id,salutation,first,middle,last,suffix,email,Phones(id,type,phone,sms,verification_token,phone_verified),Addresses(type,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)))),Phones(id,type,phone,sms,primary,verification_token,phone_verified),Addresses(id,primary,type,move_in,move_out,rent,landlord,phone,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)),Leases(id,unit_id,has_open_invoice,promotion_id,start_date,end_date,payment_cycle,bill_day,notes,terms,rent,status,send_invoice,sensitive_info_stored,auto_pay_after_billing_date,balance,open_balance,security_deposit,monthly,auction_status,LeaseAuction(id,lease_id,unit_id,auction_type,notes,created_by,scheduled_date,contact_id,amount,tax,tax_exempt,cleaning_deposit,cleaning_period,default_cleaning_deposit,default_cleaning_period,license_number,deleted_at,modified_at,payment_id,refund_id,BidInvoice(*),BuyerPremium(id,lease_auction_id,product_id,type,value,amount,is_inclusive),Contact(id,last,first,email,Phones(id,type,phone,sms))),Unit(id,property_id,category_id,address_id,number,soft_catch,late_catch,hard_catch,pin,type,state,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng)),Metrics(lifetime_payments,paid_through_date,prepaid_balance))',
		get_api: 'id,company_id,user_id,salutation,first,middle,last,suffix,email,gender,company,ssn,dob,driver_license,driver_license_city,driver_license_state,driver_license_country,driver_license_exp,active_military,have_secondary_contact,military_branch,Military(id,Phone(id,phone,sms,type,country_code),CommandingOfficer(first,last,email,Phone(id,phone,sms,type,country_code)),active,service_member_email,branch,unit_name,identification_number,service_expiration,date_of_birth,rank,Address(id,address,address2,city,state,zip,country)),Business(id,name,phone_type,phone,country_code,Address(address,address2,city,state,zip,country)),source,Reservations(id,lease_id,expires,created,time,Lease(id,unit_id,end_date,bill_day,terms,rent,promotion_id,Unit(id,property_id,category_id,number,price,state,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng)))),Employment(*),Vehicles(*),Relationships(id,related_contact_id,lease_id,type,is_alternate,is_cosigner,is_emergency,is_military,is_authorized,is_lien_holder,Contact(id,contact_id,salutation,first,middle,last,suffix,email,Phones(id,type,phone,sms),Addresses(type,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)))),Phones(id,type,phone,sms,verification_token,phone_verified),Addresses(type,move_in,move_out,rent,landlord,phone,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)),Leases(id,unit_id,promotion_id,start_date,end_date,payment_cycle,bill_day,notes,terms,rent,status,send_invoice,balance,security_deposit,monthly,Unit(id,property_id,category_id,address_id,number,type,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng))',

	},
	'/check':{
		get: 'id,company_id,user_id,lead_id,salutation,first,middle,last,suffix,email,gender,company,ssn,dob,driver_license,driver_license_state,driver_license_country,driver_license_city,driver_license_exp,active_military,military_branch,source,Employment(*),Vehicles(*),Relationships(id,related_contact_id,lease_id,type,is_cosigner,is_emergency,is_alternate,is_military,is_authorized,is_lien_holder,Contact(id,contact_id,salutation,first,middle,last,suffix,email,Phones(id,type,phone,sms),Addresses(type,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)))),Phones(id,type,phone,sms),Addresses(type,move_in,move_out,rent,landlord,phone,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)),Leases(id,unit_id,promotion_id,start_date,end_date,bill_day,notes,terms,rent,status,send_invoice,security_deposit,monthly,code,balance,decline_insurance,moved_out,rent_paid_through,lease_standing_id,insurance_exp_month,insurance_exp_year,Unit(id,property_id,category_id,address_id,number,type,status,Address(address,address2,city,state,neighborhood,zip,country,lat,lng)))'
	},
	'/:contact_id/access':{
		get: 'id,access_id,name,contact_id,property_id,pin,status,Spaces(unit_id,name,start_date,end_date,status),Property(id,company_id,address_id,number,description,status,name,access_id,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng)),Access(*))'
	},
	'/:contact_id/space-access':{
		get: 'contact_access_id,contact_id,access_id,name,soft_catch,late_catch,hard_catch,pin,unit_id,unit_number,unit_type,Property(id,company_id,address_id,number,description,status,name,access_id,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng)),Access(site_key,pin_format,site_id))'
	},
	'/:contact_id/lead':{
		get: 'id,Category(id,name,description,price),Property(id,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng),Images(*),address_id,name,number,description),Unit(id,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng),Images(*),number,price,category_id,address_id,floor,type,description,featured,available_date,status),unit_id,contact_id,property_id,category_id,address_id,created,extras,content,move_in_date,length_of_stay,lease_id,note,opened,source,status'
	},
	'/:contact_id/interactions':{
		get: 'id,entered_by,time,content,method,context,created,modified,Contact(id,company_id,first,middle,last,email,salutation,suffix),Admin(id,first,middle,last,email,salutation,suffix),Email(*)'
	},
	'/:contact_id/contact-interactions':{
		get: 'id,property_name,entered_by,space,tenant_answer,pinned,label,time,subject,context,content,method,created,entered_by,contact_id,primary_contact_id,contact_type, modified,read,notes_category,Contact(id,company_id,first,middle,last,email,salutation,suffix,Role(name),Phones(*)),EnteredBy(id,company_id,first,middle,last,email,salutation,suffix,Role(name),Phones(*)),Phone(*),Email(*),Upload(*),DeliveryMethod(*)'
	},
	'/:contact_id/activity':{
		get: 'id,activity_action_id,activity_object_id,company_id,description,link,message,created,Contact(id,company_id,first,middle,last,email,salutation,suffix),Object(id,Email(*)),ActivityObject(*),ActivityAction(*))'
	},
	'/:contact_id/reservations':{
		get: 'id,lease_id,expires,created,time,Lease(id,unit_id,start_date,end_date,bill_day,terms,rent,notes,promotion_id,Unit(id,property_id,category_id,number,price,Address(id,address,address2,city,state,neighborhood,zip,country,lat,lng)))',
	},
	'/:contact_id/uploads': {
		get: 'lease_id,unit_number,generated_by_name,uploaded_by_name,unit_type,private,id,DocumentType(*),uploaded_by,type,requires_signature,upload_date,extension,encoding,mimetype,size,name,src,signers(id,email,signed,status,Contact(id,first,last,email,Phones(id,phone,type,sms))),Revisions(iid,type,upload_date,extension,encoding,mimetype,size,name,src)'	
	}, 
	// '/:contact_id/leases': {
	// 	get: 'contact(id,first,last,company_id,email),leases(id,unit_id,start_date,end_date,payment_cycle,OpenInvoices(*),Standing(id,name),Unit(id,number,type),Property(id,name,number),Services(Product(id,name,category_type,description,default_type),id,product_id,name,price,service_type,lease_id,start_date,end_date)'	
	// }

}
