																																				

module.exports = {
	name: 'Yardi Financial Journal',
	filename:'yardi_financial_journal_export',
    fileHeader: "FinJournals",
    cols: [
        {
            label: "TRANNUM",
            key: "trannum",
            group: "yardi",
            column_type: "number",
        },
        {
            label: "PROPERTY",
            key: "prop",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "ACCOUNT",
            key: "account",
            group: "yardi",
            column_type: "number",
        },
        {
            label: "DATE",
            key: "date",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "POSTMONTH",
            key: "post_month",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "BOOKNUM",
            key: "book_num",
            group: "yardi",
            column_type: "number",
        },
        {
            label: "AMOUNT",
            key: "amount",
            group: "yardi",
            column_type: "number",
        },
        {
            label: "REMARK",
            key: "remark",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "REF",
            key: "ref",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "USERDEFINEDFIELD1",
            key: "user_defined_field_1",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "USERDEFINEDFIELD2",
            key: "user_defined_field_2",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "USERDEFINEDFIELD3",
            key: "user_defined_field_3",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "USERDEFINEDFIELD4",
            key: "user_defined_field_4",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "USERDEFINEDFIELD5",
            key: "user_defined_field_5",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "USERDEFINEDFIELD6",
            key: "user_defined_field_6",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "USERDEFINEDFIELD7",
            key: "user_defined_field_7",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "USERDEFINEDFIELD8",
            key: "user_defined_field_8",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "TAXPOINTDATE",
            key: "tax_point_date",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DESC",
            key: "description",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DOCUMENTSEQUENCENUMBER",
            key: "document_sequence_number",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILTRANAMOUNT",
            key: "detail_tran_amount",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "LEGALENTITYID",
            key: "legal_entity_id",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "BASECURRENCYID",
            key: "base_currency_id",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "TRANCURRENCYID",
            key: "tran_currency_id",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "EXCHANGERATE",
            key: "exchange_rate",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "EXCHANGERATEDATE",
            key: "exchange_rate_date",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "EXCHANGERATE2",
            key: "exchange_rate_2",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "EXCHANGERATEDATE2",
            key: "exchange_rate_date_2",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "AMOUNT2",
            key: "amount_2",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "FROMDATE",
            key: "from_date",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "TODATE",
            key: "to_date",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT1",
            key: "segment_1",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT2",
            key: "segment_2",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT3",
            key: "segment_3",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT4",
            key: "segment_4",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT5",
            key: "segment_5",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT6",
            key: "segment_6",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT7",
            key: "segment_7",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT8",
            key: "segment_8",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT9",
            key: "segment_9",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT10",
            key: "segment_10",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT11",
            key: "segment_11",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "SEGMENT12",
            key: "segment_12",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "TAXAMOUNT1",
            key: "tax_amount_1",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "TAXAMOUNT2",
            key: "tax_amount_2",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILVATTRANTYPEID",
            key: "detail_vattran_type_id",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILVATRATEID",
            key: "detail_vattran_id",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "VATTRANTYPEID",
            key: "vattran_type_id",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "VATRateId",
            key: "vat_rate_id",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DISPLAYTYPE",
            key: "display_type",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "JOB",
            key: "job",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "CATEGORY",
            key: "category",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "CONTRACT",
            key: "contract",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "COSTCODE",
            key: "costcode",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "NOTES2",
            key: "notes2",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILFIELD1",
            key: "detail_field_1",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILFIELD2",
            key: "detail_field_2",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILFIELD3",
            key: "detail_field_3",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILFIELD4",
            key: "detail_field_4",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILFIELD5",
            key: "detail_field_5",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILFIELD6",
            key: "detail_field_6",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILFIELD7",
            key: "detail_field_7",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "DETAILFIELD8",
            key: "detail_field_8",
            group: "yardi",
            column_type: "string",
        },
        {
            label: "ReverseNextMonth",
            key: "reverse_next_month",
            group: "yardi",
            column_type: "string",
        }
    ],
    offset: 1
}