<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <div class="hb-success-error-wrapper">
        <v-snackbar
            v-model="snackbar"
            light
            right
            top
            :color="backgroundColor"
            transition="slide-x-reverse-transition"
            :timeout="timeout"
        >
            <div class="pb-1 ml-n4 mr-n6 mb-1">
                <v-row no-gutters class="mt-n1 pb-2">
                    <v-col cols="10" class="pl-4 d-flex align-center">
                        <hb-icon :color="iconColor">{{ setIcon }}</hb-icon>
                        <span class="hb-success-error-title font-weight-medium pl-2 mt-n1">{{ setTitle }}</span>
                    </v-col>
                    <v-spacer></v-spacer>
                    <v-col cols="2" class="my-n1 pr-2" align="right">
                        <hb-btn icon tooltip="Close" @click="close" active-state-off :hover-background-color="closeHoverColor">mdi-close</hb-btn>
                    </v-col>
                </v-row>
                <v-divider v-if="(type !== 'generate') || complete" :style="'border:1px solid' + dividerColor"></v-divider>
                <v-progress-linear
                    v-if="(type === 'generate') && !complete"
                    background-color="#E0F5F5"
                    color="#00848E"
                    indeterminate
                    height="2"
                >
                </v-progress-linear>
                <div class="px-4 mt-4 hb-success-error-content">
                    <div>
                        {{ description }}
                    </div>
                    <ul style="list-style-type:disc;" v-if="list && list.length">
                        <li v-for="(e, i) in list" class="mt-1 mb-0" :key="'error' + i">{{ e.msg ? e.msg : e.message ? e.message : e }}</li>
                    </ul>
                    <div class="mb-0" :class="{'mt-1' : description || (list && list.length)}">
                        <slot></slot>
                    </div>
                </div>
            </div>
            <div v-if="hasFooterSlot" class="hb-success-error-footer ml-n4 mr-n6 px-4" align="right">
                <slot name="footer"></slot>
            </div>
        </v-snackbar>
    </div>
</template>
<script type="text/babel">

    import HbIcon from './HbIcon.vue';
    import HbBtn from './HbBtn.vue';
    
    export default {
        name: "HbSuccessError",
        data: function() {
            return {
                editing: false,
                hovering: false,
            };
        },
        components: {
            HbIcon,
            HbBtn
        },
        computed: {
            snackbar: {
                get () {
                    return this.value
                },
                set (value) {
                    this.$emit('input', value)
                }
            },
            hasFooterSlot(){
                return !!this.$slots['footer'];
            },
            backgroundColor(){
                switch(this.type){
                    case 'success':
                        return '#E1FAE3'
                        break;
                    case 'error':
                        return '#F8E5E1'
                        break;
                }
            },
            dividerColor(){
                switch(this.type){
                    case 'success':
                        return '#02AD0F'
                        break;
                    case 'error':
                        return '#FB4C4C'
                        break;
                    default:
                        return '#00848E'
                }
            },
            iconColor(){
                switch(this.type){
                    case 'success':
                        return '#02AD0F'
                        break;
                    case 'error':
                        return '#FB4C4C'
                        break;
                    default:
                        return '#101318'
                }
            },
            closeHoverColor(){
                switch(this.type){
                    case 'success':
                        return '#C5EDC9'
                        break;
                    case 'error':
                        return '#EFCFCC'
                        break;
                    default:
                        return '#DFE3E8'
                }
            },
            timeout(){
                switch(this.type){
                    case 'success':
                        return '6000'
                        break;
                    default:
                        return '-1'
                }
            },
            setIcon(){
                if(this.icon && this.icon.length){
                    return this.icon;
                } else {
                    switch(this.type){
                        case 'success':
                            return 'mdi-check'
                            break;
                        case 'error':
                            return 'mdi-alert'
                            break;
                        case 'generate':
                            return 'mdi-file'
                            break;
                    }
                }
            },
            setTitle(){
                if(this.title && this.title.length){
                    return this.title;
                } else {
                    switch(this.type){
                        case 'success':
                            return 'Success'
                            break;
                        case 'error':
                            return 'Warning'
                            break;
                        case 'generate':
                            return 'Generating Document'
                            break;
                    }
                }
            }
        },
        methods: {
            close(){
                this.snackbar = false;
                this.$emit('close');
            },
        },
        props: {
            value:{
                type: Boolean,
                default: false
            },
            type: {
                type: String,
                default: undefined
            },
            description: {
                type: String,
                default: undefined
            },
            list: {
                type: [Array, Object],
            },
            title: {
                type: String,
                default: undefined
            },
            icon: {
                type: String,
                default: undefined
            },
            complete: {
                type: Boolean,
                default: false
            }
        },
    }
</script>

<style scoped>

.hb-success-error-wrapper .v-snack__wrapper * {
    max-width: 351px !important;
    letter-spacing: normal !important;
}

.hb-success-error-wrapper >>> .v-snack__wrapper {
    margin: 22px !important;
}

.hb-success-error-title {
    font-size: 14px;
    color: #101318;
    line-height: 24px;
}

.hb-success-error-content {
    font-size: 12px;
    line-height: 16px;
    color: #101318;
    width: 351px !important;
}

.hb-success-error-footer {
    margin-top: 13px;
}
    
</style>