<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
  <span>
    <v-tooltip bottom :disabled="disabled" open-delay="350">
      <template v-slot:activator="{ on }">
        <v-hover v-slot:default="{ hover }">
          <span v-on="on">
            <span v-if="hasItemSlot" :class="{ 'hb-tooltip-dashed' : dashed }">
              <slot name="item"></slot>
            </span>
            <span v-else>
              <hb-icon small color="#c4cdd5" class="ml-1">mdi-information</hb-icon>
            </span>
          </span>
        </v-hover>
      </template>
      <span>
        <div class="py-1">
          <div v-if="$slots.header" class="font-weight-medium">
            <slot name="header"></slot>
          </div>          
          <div v-if="$slots.body" :class="{'pt-1' : $slots.header }">
            <slot name="body"></slot>
          </div>
        </div>
      </span>
    </v-tooltip>
  </span>
</template>

<script type="text/babel">

import HbIcon from './HbIcon.vue';

export default {
  name: "HbTooltip",
  props: {},
  data() {
    return {};
  },
  components: {
    HbIcon
  },
  computed: {
    hasItemSlot(){
        return !!this.$slots['item'];
    },
  },
  props: {
    dashed: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    }
  }
};
</script>

<style scoped>

.v-tooltip {
  position: relative;
  z-index: 99999;
}
.v-tooltip__content {
  background: #334450 !important;
  opacity: 1 !important;
}

.hb-tooltip-padding {
  padding-bottom: 2px;
}

.hb-tooltip-dashed {
  border-bottom: thin dashed;
}

</style>