apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-worker-server-ingress
  labels:
  {{- include "app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: worker.tenantinc.com
    http:
      paths:
      - backend:
          serviceName: worker-server-service
          servicePort: 80
        path: /
