build:
  image: docker:latest
  stage: build
  tags:
    - docker
    - gce
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - for TAG in r${CI_COMMIT_SHA:0:8} ${CI_COMMIT_TAG};
      do
      docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$TAG" &&
      docker push "$CI_REGISTRY_IMAGE:$TAG" &&
      echo "Pushed $TAG successfully.";
      done;

deploy_uat:
  image: dtzar/helm-kubectl:latest
  stage: deploy
  only:
    - uat
  environment:
    name: uat
  tags:
    - docker
    - gce
  script:
    - mkdir "$HOME/.kube"
    - echo "$STAGING_KUBECONFIG_BASE64" | base64 -d >"$HOME/.kube/config"
    - git clone "$OPS_GITLAB_ACCESS"
    - mkdir -p k8s-config
    - cp ops/k8s/hummingbird/pdf-generator/uat/* k8s-config/
    - "sed -i 's|image.*--ref--|image: '$CI_REGISTRY_IMAGE':r'${CI_COMMIT_SHA:0:8}'|g' k8s-config/deployment.yaml"
    - echo "Attempting to upgrade to $CI_REGISTRY_IMAGE:r${CI_COMMIT_SHA:0:8}"
    - kubectl apply -f k8s-config
    - echo "Upgrade finished."

deploy_staging:
  image: dtzar/helm-kubectl:latest
  stage: deploy
  only:
    - staging
  environment:
    name: staging
  tags:
    - docker
    - gce
  script:
    - mkdir "$HOME/.kube"
    - echo "$STAGING_KUBECONFIG_BASE64" | base64 -d >"$HOME/.kube/config"
    - git clone "$OPS_GITLAB_ACCESS"
    - mkdir -p k8s-config
    - cp ops/k8s/hummingbird/pdf-generator/staging/* k8s-config/
    - "sed -i 's|image.*--ref--|image: '$CI_REGISTRY_IMAGE':r'${CI_COMMIT_SHA:0:8}'|g' k8s-config/deployment.yaml"
    - echo "Attempting to upgrade to $CI_REGISTRY_IMAGE:r${CI_COMMIT_SHA:0:8}"
    - kubectl apply -f k8s-config
    - echo "Upgrade finished."

deploy_production:
  image: dtzar/helm-kubectl:latest
  stage: deploy
  only:
    - master
  environment:
    name: master
  tags:
    - docker
    - gce
  script:
    - mkdir "$HOME/.kube"
    - echo "$STAGING_KUBECONFIG_BASE64" | base64 -d >"$HOME/.kube/config"
    - git clone "$OPS_GITLAB_ACCESS"
    - mkdir -p k8s-config
    - cp ops/k8s/hummingbird/pdf-generator/production/* k8s-config/
    - "sed -i 's|image.*--ref--|image: '$CI_REGISTRY_IMAGE':r'${CI_COMMIT_SHA:0:8}'|g' k8s-config/deployment.yaml"
    - echo "Attempting to upgrade to $CI_REGISTRY_IMAGE:r${CI_COMMIT_SHA:0:8}"
    - kubectl apply -f k8s-config
    - echo "Upgrade finished."

